# Generated by Django 4.2.9 on 2024-02-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
